"""Initial migration local

Revision ID: 7e3b96a1d063
Revises: e26dc9413cc5
Create Date: 2026-01-17 19:09:29.117585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3b96a1d063'
down_revision = 'e26dc9413cc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
