"""Sync models

Revision ID: cfeb318bbc6e
Revises: 7e3b96a1d063
Create Date: 2026-01-17 19:37:04.873184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfeb318bbc6e'
down_revision = '7e3b96a1d063'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
