
worker_processes  1;
error_log  /Users/jeongseongchae/dev/owner/surplus-hub-web/deployment/error.log;
pid        /Users/jeongseongchae/dev/owner/surplus-hub-web/deployment/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    # Logs
    access_log  /Users/jeongseongchae/dev/owner/surplus-hub-web/deployment/access.log;
    
    # Temp Paths (Required for running without root)
    client_body_temp_path /Users/jeongseongchae/dev/owner/surplus-hub-web/deployment/client_body_temp;
    proxy_temp_path       /Users/jeongseongchae/dev/owner/surplus-hub-web/deployment/proxy_temp;
    fastcgi_temp_path     /Users/jeongseongchae/dev/owner/surplus-hub-web/deployment/fastcgi_temp;
    uwsgi_temp_path       /Users/jeongseongchae/dev/owner/surplus-hub-web/deployment/uwsgi_temp;
    scgi_temp_path        /Users/jeongseongchae/dev/owner/surplus-hub-web/deployment/scgi_temp;

    # Optimization
    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;

    # Gzip
    gzip  on;
    gzip_vary on;
    gzip_min_length 1000;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    server {
        listen       8081;
        server_name  localhost;

        root   /Users/jeongseongchae/dev/owner/surplus-hub-web;
        index  index.html;

        error_page  404 /404.html;

        # v1.1
        location /v1_1/ {
            alias /Users/jeongseongchae/dev/owner/surplus-hub-web/surplus_hub_landing_page_v1_1/;
            try_files $uri $uri/ /v1_1/index.html;
            expires 1d;
        }

        # v1.2
        location /v1_2/ {
            alias /Users/jeongseongchae/dev/owner/surplus-hub-web/surplus_hub_landing_page_v1_2/;
            try_files $uri $uri/ /v1_2/index.html;
            expires 1d;
        }

        # v2.0
        location /v2/ {
            alias /Users/jeongseongchae/dev/owner/surplus-hub-web/surplus_hub_landing_page_v2/;
            try_files $uri $uri/ /v2/index.html;
            expires 1d;
        }

        # Assets
        location ~* \.(jpg|jpeg|png|gif|ico|svg)$ {
            expires 7d;
        }
    }
}
